#ifndef CONFIG_H
#define CONFIG_H

#include <SDL2/SDL.h>

#define EMULAOR_WINDOW_TITLE "CHIP-8 Emulator"

#define PIXEL_SIZE 10
#define DISPLAY_WIDTH 64
#define DISPLAY_HEIGHT 32
#define DISPLAY_SIZE DISPLAY_WIDTH *DISPLAY_HEIGHT

#define MEMORY_SIZE 4096
#define REGISTER_COUNT 16
#define STACK_SIZE 16
#define CHARACTER_SET_SIZE 80
#define CHARACTER_SET_HEIGHT 5
#define CHARACTER_SET_START_ADDRESS 0x00
#define PROGRAM_START_ADDRESS 0x200

#define KEY_COUNT 16

#define CYCLES_PER_SECOND 500
#define CYCLES_PER_FRAME 10


#endif